SET FOREIGN_KEY_CHECKS=0;
truncate bevet;
truncate cikk;
truncate cikkcsoport;
truncate cim;
truncate ember;
truncate emberraktarkapcsolo;
truncate megye;
truncate orszag;
truncate partner;
truncate partnercimek;
truncate raktar;
truncate varos;
truncate osztaly;
SET FOREIGN_KEY_CHECKS=1;
insert into cikkcsoport(nev,lejarat)value("Munkaruha",1);
insert into cikkcsoport(nev,lejarat)value("Eszközök",9999);
insert into cikkcsoport(nev,lejarat)value("Védőruha",9999);
insert into cikkcsoport(nev,lejarat)value("Védőfelszerelés",2);

insert into osztaly(nev)value("raktár");
insert into ember(nev,osztalyid)value("raktár",1);
truncate ember;
insert into user(username,password,fullname)value("Misi","tempUser","Pekár Mihály");
select * from ember;
select * from osztaly;
select * from cikk;
select * from emberraktarkapcsolo;
select * from cikkcsoport;
update cikkcsoport set lejarat =  9999 where id not in (1,4) ;
select * from emberraktarkapcsolo;
select e.nev as "name",c.cikknev as "item",i.mennyiseg as "count", i.egysegar as "price" from emberraktarkapcsolo ek join ember e on (ek.emberid = e.id ) join raktar i on (i.id = ek.raktarid) join cikk c on (i.cikkid = c.id) where emberid != 1 and  (c.cikkcsoport = 1 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 1 YEAR)) or (c.cikkcsoport = 4 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 2 YEAR)) ;
select * from raktar;
update raktar set kiad = DATE_ADD(kiad, INTERVAL -2 YEAR) where id = 19 ;
update raktar set mennyiseg = 2 where id = 6;
select * from emberraktarkapcsolo;
select * from bevet;
select * from partner;
select COUNT(ember.id), SUM(i.mennyiseg) from emberraktarkapcsolo ek left join ember on(ek.emberid = ember.id) left join raktar emk on (ek.raktarid = emk.id ) left join cikk c on (emk.cikkid = c.id) left join cikkcsoport cs on(c.cikkcsoport = cs.id) inner join partner on (emk.partnerid = partner.id) where ek.emberid = 1 and mennyiseg > 0;
select e.nev as "name",c.cikknev as "item",i.mennyiseg as "count", i.egysegar as "price" from emberraktarkapcsolo ek join ember e on (ek.emberid = e.id ) join raktar i on (i.id = ek.raktarid) join cikk c on (i.cikkid = c.id) where emberid != 1 and  (c.cikkcsoport = 1 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 1 YEAR)) or (c.cikkcsoport = 4 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 2 YEAR)) ;
select emk.id as ID, ember.Nev as "storagename" ,c.cikkszam as "number", c.cikknev as "name",  c.cikkcsoport as "groupid", cs.nev as "group" ,emk.mennyiseg as "count", c.mertekegyseg as "unit", emk.egysegar as "price",  emk.hasznalt as "used", date_format(emk.bevdatum, '%Y-%m-%d') as "date", partner.nev as "Partner" from emberraktarkapcsolo ek left join ember on(ek.emberid = ember.id) left join raktar emk on (ek.raktarid = emk.id ) left join cikk c on (emk.cikkid = c.id) left join cikkcsoport cs on(c.cikkcsoport = cs.id) inner join partner on (emk.partnerid = partner.id) where ek.emberid = 1 and mennyiseg > 0;
select COUNT(DISTINCT(e.id)) as ember, SUM(i.mennyiseg) as cikk from emberraktarkapcsolo ek join ember e on (ek.emberid = e.id ) join raktar i on (i.id = ek.raktarid) join cikk c on (i.cikkid = c.id) where emberid != 1 and  i.mennyiseg > 0 and (c.cikkcsoport = 1 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 1 YEAR)) or (c.cikkcsoport = 4 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 2 YEAR)) ;
insert into autodeleteditem select e.nev as "name",c.cikknev as "item",i.mennyiseg as "count", i.egysegar as "price" from emberraktarkapcsolo ek join ember e on (ek.emberid = e.id ) join raktar i on (i.id = ek.raktarid) join cikk c on (i.cikkid = c.id) where emberid != 1 and  (c.cikkcsoport = 1 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 1 YEAR)) or (c.cikkcsoport = 4 and SYSDATE() > DATE_ADD(i.kiad, INTERVAL 2 YEAR)) ;
